### ISSUE TITLE
Header can block out body

### ISSUE THREAD

**Issue by justparking** [justparking/feature_nodeluiunify#26]
Shown here, part of the main page is blocked and unclickable.

![image](https://user-images.githubusercontent.com/5266533/60628864-c1e5db80-9e36-11e9-8650-e3ddefac0e77.png)

This only seems to occur if the node self refreshes (say because of restart) and the width is too small. Easy to reproduce.

**Comment by mcartmel** [comment]
Fixed.

**Comment by justparking** [comment]
This is still occuring or at least on the `/nodes.xml#List` page I was looking at.

**Comment by mcartmel** [comment]
The page you sent me wasn't using the latest code.
